nohup: ignoring input
1 4 0.01 20000 0.0 ['dw, dr, hvac, mw, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, dr, hvac, mw, fridge' is not in list
1 4 0.01 20000 0.0 ['dw, dr, fridge, hvac, mw']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, dr, fridge, hvac, mw' is not in list
1 4 0.01 20000 0.0 ['dw, dr, fridge, mw, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, dr, fridge, mw, hvac' is not in list
1 4 0.01 20000 0.0 ['dw, dr, mw, hvac, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, dr, mw, hvac, fridge' is not in list
1 4 0.01 20000 0.0 ['dw, dr, mw, fridge, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, dr, mw, fridge, hvac' is not in list
1 4 0.01 20000 0.0 ['dw, mw, hvac, fridge, dr']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, mw, hvac, fridge, dr' is not in list
1 4 0.01 20000 0.0 ['dw, mw, hvac, dr, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, mw, hvac, dr, fridge' is not in list
1 4 0.01 20000 0.0 ['dw, mw, fridge, hvac, dr']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, mw, fridge, hvac, dr' is not in list
1 4 0.01 20000 0.0 ['dw, mw, fridge, dr, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, mw, fridge, dr, hvac' is not in list
1 4 0.01 20000 0.0 ['dw, mw, dr, hvac, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, mw, dr, hvac, fridge' is not in list
1 4 0.01 20000 0.0 ['dw, mw, dr, fridge, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'dw, mw, dr, fridge, hvac' is not in list
1 4 0.01 20000 0.0 ['mw, hvac, fridge, dr, dw']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, hvac, fridge, dr, dw' is not in list
1 4 0.01 20000 0.0 ['mw, hvac, fridge, dw, dr']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, hvac, fridge, dw, dr' is not in list
1 4 0.01 20000 0.0 ['mw, hvac, dr, fridge, dw']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, hvac, dr, fridge, dw' is not in list
1 4 0.01 20000 0.0 ['mw, hvac, dr, dw, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, hvac, dr, dw, fridge' is not in list
1 4 0.01 20000 0.0 ['mw, hvac, dw, fridge, dr']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, hvac, dw, fridge, dr' is not in list
1 4 0.01 20000 0.0 ['mw, hvac, dw, dr, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, hvac, dw, dr, fridge' is not in list
1 4 0.01 20000 0.0 ['mw, fridge, hvac, dr, dw']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, fridge, hvac, dr, dw' is not in list
1 4 0.01 20000 0.0 ['mw, fridge, hvac, dw, dr']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, fridge, hvac, dw, dr' is not in list
1 4 0.01 20000 0.0 ['mw, fridge, dr, hvac, dw']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, fridge, dr, hvac, dw' is not in list
1 4 0.01 20000 0.0 ['mw, fridge, dr, dw, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, fridge, dr, dw, hvac' is not in list
1 4 0.01 20000 0.0 ['mw, fridge, dw, hvac, dr']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, fridge, dw, hvac, dr' is not in list
1 4 0.01 20000 0.0 ['mw, fridge, dw, dr, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, fridge, dw, dr, hvac' is not in list
1 4 0.01 20000 0.0 ['mw, dr, hvac, fridge, dw']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dr, hvac, fridge, dw' is not in list
1 4 0.01 20000 0.0 ['mw, dr, hvac, dw, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dr, hvac, dw, fridge' is not in list
1 4 0.01 20000 0.0 ['mw, dr, fridge, hvac, dw']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dr, fridge, hvac, dw' is not in list
1 4 0.01 20000 0.0 ['mw, dr, fridge, dw, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dr, fridge, dw, hvac' is not in list
1 4 0.01 20000 0.0 ['mw, dr, dw, hvac, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dr, dw, hvac, fridge' is not in list
1 4 0.01 20000 0.0 ['mw, dr, dw, fridge, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dr, dw, fridge, hvac' is not in list
1 4 0.01 20000 0.0 ['mw, dw, hvac, fridge, dr']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dw, hvac, fridge, dr' is not in list
1 4 0.01 20000 0.0 ['mw, dw, hvac, dr, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dw, hvac, dr, fridge' is not in list
1 4 0.01 20000 0.0 ['mw, dw, fridge, hvac, dr']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dw, fridge, hvac, dr' is not in list
1 4 0.01 20000 0.0 ['mw, dw, fridge, dr, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dw, fridge, dr, hvac' is not in list
1 4 0.01 20000 0.0 ['mw, dw, dr, hvac, fridge']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dw, dr, hvac, fridge' is not in list
1 4 0.01 20000 0.0 ['mw, dw, dr, fridge, hvac']
Traceback (most recent call last):
  File "cnn-tree.py", line 279, in <module>
    train_fold, valid_fold, test_fold, train_error, valid_error, test_error, train_losses, valid_losses, test_losses = disagg_fold(dataset, fold_num, lr, p)
  File "cnn-tree.py", line 114, in disagg_fold
    out_train, out_valid, out_test = preprocess(train, valid, test)
  File "cnn-tree.py", line 86, in preprocess
    torch.Tensor(train[:, APPLIANCE_ORDER.index(appliance), :, :].reshape((train.shape[0], 1, -1, 24))))
ValueError: 'mw, dw, dr, fridge, hvac' is not in list
